# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dbb8ccfed8ed1e440f4e94e8d17147956433adca23ebc845d25fad37f36aedd5406bb078fdc11a27f7789a58d80b3d38e502e55cb6890032b9bbbf295b13e39

test:
  secret_key_base: 6b471bacac43b57fba4c57d0ca824b85b9b54d150091e2fdb7f319d6245bda5b8eecc5dd6cc13ef4b56c3f603b420b566e4d75e896d7a2b92f9c1a43d7b0aa0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
